### ISSUE TITLE
macosx/x86.32 gc / segfault error

### ISSUE THREAD

**Issue by bjourne** [factor/factor#1513]
It crashes with:

```
Loading resource:extra/zoneinfo/zoneinfo-tests.factor
Unit Test: { { t } [ "PST8PDT" find-zone-rules and >boolean ] }
fatal_error: Memory protection fault during gc: 0x660
Launcher error:
Process was killed as a result of a call to
kill-process, or a timeout
```

It started happening around November 19, so it is probably this a3be724f5a149cde60d8d6fd8e89723b35569a5f or this 097b40ce4107e824acd83fdf1c024596e692f7d0 or maybe even this a915d3bdb4eaaa12a85073a7e9abb1fe700d689b commit that caused it.

**Comment by bjourne** [comment]
Looks like this is the only remaining big but that the build servers pick up? I don't have a mac so I can't reproduce it, but I'm sure the regression was caused in one of the compiler fixing commits I pushed in nov 14 - nov 18. 

So my idea is to revert one commit, see if it makes the build bot happy, if not undo and revert the next suspected commit. That causes a lot of repository noise but I can't think of a better way.

**Comment by mrjbq7** [comment]
Maybe we can give you remote access to a Mac to shell in and try a few patches out? @erg?

**Comment by bjourne** [comment]
Yes. It would also help if we could bisect the crash somehow. Like figure out the last commit where the bug is not present, and the first commit where it for sure is. The bug is probably something trivial, but it is hard to spot it because there are so many commits to investigate.

**Comment by bjourne** [comment]
Interesting that it crashes on the absolutely last test `load-all test-all` runs. Maybe it is not crashing in the test, but when it tries to return to the listener prompt.

**Comment by bjourne** [comment]
I'm curious if you Mac people can also see the crash when you build Factor for 32bit? Maybe this is something that only happens on that particular system for some reason?

**Comment by mrjbq7** [comment]
I can reproduce the crash locally but haven't had time to do any debugging. It's only when you do a load-all and test-all. Tried to test all the vocabs separately and seemed okay.  Little bit of heisenbugs.

**Comment by bjourne** [comment]
Last clean build I see: 2015-11-16 gitid a3be724f5a149cde60d8d6fd8e89723b35569a5f

First failing build I see: 2015-11-19 gitid 6d21a5a0731e6d5f0396673c5f7966434640a5c5

So a list of possible commits causing the error:

* a915d3bdb4eaaa12a85073a7e9abb1fe700d689b (somewhat suspect.. there could be a typo!)
* a3be724f5a149cde60d8d6fd8e89723b35569a5f (very suspect)
* 097b40ce4107e824acd83fdf1c024596e692f7d0 (was comitted after Nov 19, so probably not suspect)
* e1b22e0af4e5fa6aff7551c3280bfe02e728caa3 (also after Nov 19)

Tag macro refactorings. These were all after Nov 19 but they touch the gc:

* a8aaa4288231a2395070c5b0ea4c43939bf81c63 (Nov 22)
* 22bb0cfecfc5c09953b613e3ad01d2a713585ea7 (also Nov 22)
* 0274e889b94323fdde6919a77c494ffcfbcb2166
* 867c85f1c50ce9276affa8d430cdf125a818b2d6

So if you dont mind, I'll soon try and revert a915d3bdb4eaaa12a85073a7e9abb1fe700d689b and a3be724f5a149cde60d8d6fd8e89723b35569a5f and see if that helps.

**Comment by mrjbq7** [comment]
Maybe I can try reverting and testing locally.  It takes awhile to prove that it works or not.

**Comment by bjourne** [comment]
a3be724f5a149cde60d8d6fd8e89723b35569a5f is exonerated. Remaining suspects are: a915d3bdb4eaaa12a85073a7e9abb1fe700d689b, a8aaa42, 22bb0cf, 0274e88, 867c85f, a915d3b, 097b40c, e1b22e0

**Comment by bjourne** [comment]
Few more tests. Remaining: a915d3bdb4eaaa12a85073a7e9abb1fe700d689b, a8aaa4288231a2395070c5b0ea4c43939bf81c63, 0274e889b94323fdde6919a77c494ffcfbcb2166, 867c85f1c50ce9276affa8d430cdf125a818b2d6, a915d3bdb4eaaa12a85073a7e9abb1fe700d689b and e1b22e0af4e5fa6aff7551c3280bfe02e728caa3

**Comment by bjourne** [comment]
So this new change I pushed should do it. After bootstrap image update. If it doesn't, then I don't understand anything.

**Comment by mrjbq7** [comment]
I pushed new boot images and an unrelated commit which should trigger new builds.

**Comment by bjourne** [comment]
Still crashing so I reverted it. New boot images are required again I'm afraid. Perhaps the bug is in the commits relating to the linked-hash changes that happened in November. Perhaps there is a relation between this and the #1484 bug.

**Comment by mrjbq7** [comment]
I just tried a ``load-all` and ``test-all`` of a clean build, and it didn't crash.  I had 143 test failures from things like ``db`` where I didn't have MySQL or PostgreSQL installed.  I wonder if we have some kind of corruption where one test causes the failure later?

**Comment by mrjbq7** [comment]
Or as @erg pointed out, maybe the mac build machine is in a borked state.  I want to look at that as a possibility soon.

**Comment by bjourne** [comment]
I guess due to the revert I made, a new set of boot images is needed.

**Comment by mrjbq7** [comment]
I think I pushed new images, but I'm not sure what my username/password is to be able to increment the build counter to make a new build.  @erg?  It should work on the next commit.

Also, what do you think about my theory of "some other test corrupts mac-32 so it crashes later"?

**Comment by bjourne** [comment]
That absolutely could be it. It always crashes at the same test which is weird. It says "Memory protection fault during gc: 0x6c0" Sometimes the constant is 0x6b0 or 0x6e0 instead. Probably it is a fixnum holding an array index 107, 108, 110... That's why I thought the error could be in a3be724f5a149cde60d8d6fd8e89723b35569a5f or 097b40ce4107e824acd83fdf1c024596e692f7d0 because they could impact how the compiler generates code for iterating arrays. 

And "Memory protection fault during gc: 0x6c0" sounds like it tries to follow a pointer which is not a real pointer but a pointer to a fixnum.

**Comment by bjourne** [comment]
I wonder is the build server building with debug enabled? If it isn't then maybe it should be. The debug build is much slower but it has much more assert checking so it could offer some clues.

**Comment by mrjbq7** [comment]
Maybe @erg can kick off a manual build of ``macosx-x86-32`` with ``DEBUG`` on, and then do a ``load-all`` and ``test-all``.

**Comment by bjourne** [comment]
Now remaining from my original list: 867c85f1c50ce9276affa8d430cdf125a818b2d6

Other commits that can be interesting to test: 63fd4d25cfd7abf3937124fcd3a4d7db86a9e6a6, 1421779c9e319eea43bd4dc99e833d075861a1dd, 17b536c3a8996fe7f56d3f142ac107b01f25f776, 6d21a5a0731e6d5f0396673c5f7966434640a5c5, 7301da03146553e0c9eca7bcd1ffa397439b5d9d, a97f840daaaa9e0768b5d1b40ab5d01431c7db64, d211bee38b9f3f3b88fa5f3887384ecf64a62781, 02c4ec36308ebbb3abb28cbfaeaf4de61d837066, bda9092ceff69accc8ea201fe3c96a8ddfea2dfe, 3c06b585d7c1548b71b05dd592905885215815d4, a73340a032c60e457d6e0b9a50a4285772328c81, f7b7b5afbf419cc8ea06e1c55e21b9bb5a32cecd, 40d454758e364b25cd623bdb65b411163da3de80, 3718137969b169efc9529a95d3b067b4801f6e6c, f692200547594e3a9f36f7896419490b4ea1867d, cfe4fec574293cc97654ad5d12cb94137ee8e98c There must be something in one of those commits that triggered the error...

**Comment by mrjbq7** [comment]
It's so strange, we don't usually get such platform-specific heisenbugs.

Also, after I added timeouts to the process streams, we get a ``build-support`` vocab test failure on linux-32.  Haven't looked at that yet.

**Comment by bjourne** [comment]
Maybe that's a default timeout it exceeds? Running the build command probably takes a very long time.

**Comment by mrjbq7** [comment]
@bjourne I'm trying to bootstrap right now and it seems to hang at "Stage 2 early init...":

```
$ [master*] ./factor -i=boot.unix-x86.64.image
*** Stage 2 early init... 
```

Any idea what that is?

**Comment by bjourne** [comment]
Oh the fixnum cast wasn't right to remove. I have reverted it now.

**Comment by mrjbq7** [comment]
Closing since we don't support mac 32-bit.
