### ISSUE TITLE
FUEL: Incorrect highlighting of words starting with a number

### ISSUE THREAD

**Issue by AlexIljin** [factor/factor#1800]
In Emacs words like `2bi`, `3drop`, `4array` are incorrectly highlighted as if they were numbers, instead of identifiers.

**Comment by mrjbq7** [comment]
@bjourne

**Comment by bjourne** [comment]
Are you using FUEL from git Alex? That problem should have been fixed a long while ago.

**Comment by AlexIljin** [comment]
Yes, I was using FUEL from git, and I saw the issue on my Spacemacs when I reported it (March 23rd).

I have just checked now, and I still see it. In this line `6420 2dip 2first 2dip dip first first2` the first four words have a color different from the last three words, which makes me think that the former are colored as numbers instead of as identifiers.

Spacemacs v0.200.9.

**Comment by bjourne** [comment]
I don't know how Spacemacs works. But try and add this to the end of your `~/.spacemacs` file:

    (add-to-list 'load-path "/path/to/factor/misc/fuel")
    (setq fuel-factor-root-dir "/path/to/factor")
    (require 'factor-mode)
    (require 'fuel-mode)

Im guessing that there is some old factor-mode from elpa or something installed on your machine and it could interfere with the git version.

**Comment by alex-ilin** [comment]
@bjourne: how can I point at something in Emacs and find out what coloring it is using? Are all things classified into categories (number, identifier, string, comment, etc.) and if so how can I query the category of the thing at point?
