### ISSUE TITLE
Paleo-history of Factor

### ISSUE THREAD

**Issue by nomennescio** [factor/factor#2190]
The current Git archive of Factor goes back to the initial Git import 2007-09-21 by Slava. The archive contains release tags for versions 0.94 - 0.98. What's missing is the history of the development of Factor before that date.

Using 'git replace' it is possible to insert such older history, if it is still available from the original CVS and Darcs archives (I think). Although it does not serve a direct purpose, it is interesting to trace older developments.

Are these older archives still around somewhere? I probably would be able to recreate an accurate Git history out of them.

**Comment by slavapestov** [comment]
There are some old versions up at https://downloads.factorcode.org/releases/.

**Comment by nomennescio** [comment]
Hi Slava! First of all: thanks for Factor! I noticed the old Darcs url is not working anymore, and neither is the CVS repo that used to be at SourceForge. Are there still any copies of those available?

**Comment by slavapestov** [comment]
You might be able to get access to the CVS repo if you ask @erg to enable it again.

**Comment by nomennescio** [comment]
Will ask him, thanks.

**Comment by erg** [comment]
Sourceforge seems to have deleted their bread and butter CVS repository hosting options, but I found one from an old backup. I also forgot how to run CVS, it might be incomplete.

We also used darcs for awhile, I can probably find a darcs repo too.

https://downloads.factorcode.org/factor-cvs.tar.gz

**Comment by erg** [comment]
I found a darcs repo.

https://downloads.factorcode.org/factor-darcs.tar.gz

**Comment by nomennescio** [comment]
Wow, thanks! I'll see what I can do with that

**Comment by nomennescio** [comment]
Hi @erg, the CVS tar.gz is just a working copy, not the CVS repo itself, and does not contain history. The CVS repo should reside in (a subdirectory of) CVSROOT, and would include *,v files.

**Comment by nomennescio** [comment]
@erg: the Darcs repository has history from 2006-02-01 (initial import) until 2006-12-20, whereas the Git repo initial import is at 2007-09-21, which is a gap of 10 months. I suppose that would still contain additional commits. The original Darcs repo at https://www.factorcode.org/old/repos/Factor/ gives a '404'.

**Comment by nomennescio** [comment]
Converted Darcs to Git, following ordering of Darcs commits. Contains release tags 0.81 to 0.86 and partial history towards 0.87. Will publish in case no better Darcs archive turns up.

**Comment by nomennescio** [comment]
The current git archive starts with version 0.91. So history for versions 0.0 - 0.80/0.81 and 0.87-0.90/0.91 are still to be located.

**Comment by erg** [comment]
It might be lost.

@doublec Do you have a deep clone of the cvs repository?

**Comment by nomennescio** [comment]
Or maybe these can be located on a backup of factorcode.org?

**Comment by doublec** [comment]
@erg I have some old repositories around, I'll have to look through my backups. I have an older darcs repository but it's one I did myself with periodic bulk imports from CVS - it doesn't contain the actual CVS history. I'll look through the backups on the weekend and see if I can find anything more useful.

**Comment by doublec** [comment]
@erg @nomennescio Try this http://cd.pn/factor-cvs.tar.bz2

**Comment by doublec** [comment]
That gives versions from about 0.60-0.80.

**Comment by doublec** [comment]
Version 0.58 is available with source in the JAR file: https://web.archive.org/web/20040604012051/www.jedit.org/factor/

It was announced on the concatenative mailing list on 15 April 2004, a couple of months before that version, but I can't find anything older. I think @slavapestov probably had a private CVS repos for development before sourceforge.

**Comment by erg** [comment]
@doublec Great find! All that we're missing is some of the darcs repo now?

**Comment by erg** [comment]
I put the factor-cvs up on downloads.factorcode.org as well.

https://downloads.factorcode.org/factor-cvs.tar.bz2

**Comment by nomennescio** [comment]
I will have a go at the CVS archive. As for old versions, https://downloads.factorcode.org/releases/ has a string of them, many include sources. So a partial release history could be reconstructed from them, but that of course lack all the intermediate commits and their messages.

**Comment by nomennescio** [comment]
For CVS conversion I need to convert CVS username into author and email addresses. I can guess those partially from later Darcs and Git commits, but am still left with some unknowns. Could someone fill these in from their past knownledge?

spestov, Slava Pestov, slava@factorcode.org
doublec, Chris Double, chris.double@double.co.nz
erg, Doug Coleman, erg@trifocus.net
littledan, Daniel Ehrenberg, microdan@gmail.com
dharmatech, Eduardo Cavazos, wayo.cavazos@gmail.com

svuori, Sampo Vuori, sampo@kingi (no full email known, has presence on GitHub?)
trentbuck, Trent Buck,
eiz,
root,
wrunt,

**Comment by erg** [comment]
I think it doesn't matter. My erg@trifocus email is defunct. You could just give them @factorcode.org emails.

**Comment by nomennescio** [comment]
Email is not that important, but using correct names is a nice gesture. For now I will keep the login names. If needed a Git rewrite of history can be done.

**Comment by doublec** [comment]
@nomennescio Can you edit your comment and remove my email address please?

**Comment by nomennescio** [comment]
Is adding the emails to Git a problem?

**Comment by doublec** [comment]
@nomennescio I'm fine with adding them in git, I just didn't want it in a github issue comment. It's a pain having old emails all over the place but for history like git it's fine.

**Comment by nomennescio** [comment]
@doublec did you find a more complete Darcs repo?

**Comment by nomennescio** [comment]
I'm convinced @slavapestov did indeed have his own private CVS repo; when comparing imports I can see the following diff

- * $Id: Cons.java,v 1.9 2004/04/11 20:37:03 slava Exp $
+ * $Id: Cons.java,v 1.2 2004/07/19 20:10:17 spestov Exp $

i.e. a later revision by date has a LOWER file version.
Any chance that is still lying around somewhere?

**Comment by nomennescio** [comment]
@erg I've recreated a partial history from the supplied CVS and Darcs archive that could be found, as well as from the release snapshots.  To make it work for the existing repo, I've created a replacement object for the Git root, that will have as parent the last Darcs commit. Using replacement objects requires some user interaction, as these need to be explicitly fetched and are not automatically cloned. As an alternative, I could do rewrite of the whole archive, in which case the replacement object is not necessary. That's also has some downsides.

What do you prefer?

**Comment by AlexIljin** [comment]
@nomennescio, I would strongly advise against the full rewrite: all commit IDs will become different, which will break relation to all cloned repos.
Replacement parent is the way to go, IMO, but what was that about them not being cloned? (This may actually be good for those not interested in too much history.)

**Comment by nomennescio** [comment]
Although rewriting has some drawbacks, again it's not that big of an issue; it would require some updating on the part of developers, but again, there are not that many people actively pushing into the archive.

As for the history, you will get all of it if my pull request will be accepted, but the TOTAL history is on my side 230 MB, which now includes ALL boot images for ALL platforms for ALL releases.

The only thing NOT being automatically cloned will be the replacement object for the first git commit, which will link it to previous commits. That would need to be updated by hand.

git fetch <repo> 'refs/replace/*:refs/replace/*'

or add it to your git remote configuration, after which all future replace objects will be fetched automatically if you do

git fetch <repo>

That is something ALL users would have to do, not just developers pushing code, hence the question on the rewrite.

Alas, there's no automagic solution currently in Git.

**Comment by jonenst** [comment]
I'm also against rewriting the whole history. Also against committing all
the images, keeping the history small is important.

Le sam. 19 oct. 2019 à 10:16, nomennescio <notifications@github.com> a
écrit :

**Comment by timor** [comment]
I also am not a big fan of rewriting. Having said that, there were a couple of times already where I wanted to dig deeper into the history, so having a branch around to check that if necessary would be helpful.

**Comment by nomennescio** [comment]
I've made a pull request for the history, which contains a single replace object for the Git root parent. See #2197, which might require a full rewrite of Git history anyway.

**Comment by nomennescio** [comment]
Tried to create a pull request for 'release' only, but Github just can't handle it, and tries to make a weird merge out of it. My local repo shows an absolute fine history which is nicely integrated into the current Git main. The only way forward seems for me to push directly into the Git archive (as I did with the fork), or some of the maintainers pulls it out of my fork.

**Comment by mrjbq7** [comment]
It's easy enough to pull from your fork if you tell us which branch, etc.

But we need to decide best path forward. 

I'm not opposed to re-writing history, but we need to make sure the new history is a correct version of history, and present code.

**Comment by erg** [comment]
Github has been willing to do server-side commands in the past. We probably don't need them to intervene, but it's an option.

**Comment by nomennescio** [comment]
@mrjbq7 

For the branches, see above: just fetch cvs, darcs, and release.
Then a pull from master for a single commit on README.md which documents how to retrieve replace object.
Then get that replace object as by these instructions.

I do not touch the current Git repo, everything stays as it is, these are just extra branches with all the history. The replace object will modify the parent of the root of the current archive to point into previous historical commits. 

Rewriting is not necessary for this, but might be necessary for #2197 
As a bonus, then the replace object is not needed anymore.

**Comment by nomennescio** [comment]
To summarize; no rewriting is needed to import the added history from my fork. Rewriting is probably needed for #2197 , in which case the history on the release branch might need to be adjusted for import-0.94, import-0.95, and import-0.96 before such a rewrite. As a bonus, after a rewrite the replace objects are not needed anymore.

**Comment by nomennescio** [comment]
@mrjbq7 @erg @doublec Any thoughts on how to proceed yet? I think my proposal for just fetching is quite harmless. I would like to be able to at least create a pull request out of my fork for the single commit on 'master', before creating additional pull requests for other issues I've reported, to avoid unforeseen Github side effects.

**Comment by mrjbq7** [comment]
I haven’t had a chance to look at it. 

Not sure what you mean by a single commit in master but maybe keep it in a branch for a smidge linger. 

I’ll get some time next day or two.

**Comment by nomennescio** [comment]
I can wait a bit longer, no problem

**Comment by nomennescio** [comment]
@mrjbq7 I think I need to start creating local branches to not block any other contributions I want to make. I'm not sure on how you guys handle branches on forks, can you clarify?

**Comment by nomennescio** [comment]
Created pull request of sinlge master commit, which only lists how to generally handle replace objects.

**Comment by mrjbq7** [comment]
Typically, you would have a feature branch and make a pull request.  If you depend on it, there might be some local git stuff you might have to do for a bit.  But keeping it in your master has the problem that your master is not in sync and if that's important to you, could cause issues if we haven't pulled it yet.

**Comment by mrjbq7** [comment]
Which branch has the history you want merged?

**Comment by nomennescio** [comment]
The history must NOT be pulled/merged. Just 'git fetch' the branches **cvs**, **darcs**, and **release**, as by the above instructions. Automagically you will see a merged tree.

**Comment by nomennescio** [comment]
Postponing importing this history will only work until the first rewrite of the current archive. Then I would need to make a completely new history again, which is a lot of manual labor. Doing it twice is a bit too much.

**Comment by mrjbq7** [comment]
I pushed ``cvs`` and ``darcs`` branches.

But, the ``release`` branch was giving me trouble.

Is the release branch just individual releases?  If so, the binaries or source downloads are probably sufficient to maintain?

**Comment by nomennescio** [comment]
The release branch contains source snapshots. Because the darcs and cvs repos were incomplete, the release branch contains missing source code. Next to that it has accurate (but see #2197) tags for releases. It makes it possible to trace developments prior to release 0.66, and between releases 0.86 and 0.91, for which no CVS or Darcs history is currently available. It makes it possible to see diffs in Git GUI/Gitk between these changes, which is better than only having separate source downloads.

**Comment by nomennescio** [comment]
What trouble did you experience with the `releae` branch? Can I help?

**Comment by nomennescio** [comment]
I see you also didn't fetch the tags yet, nor the replace object that connects 'darcs' to 'master', is that on purpose?

**Comment by erg** [comment]
What's left here?

**Comment by nomennescio** [comment]
Import is not completely done yet. See my comments above.

**Comment by erg** [comment]
Ok, I did a git fetch from your repo and then did ``git push --tags`` to github.

Also I merged the README.md PR.

What did I screw up❓ 

Let's do #2197 next somehow. Thank you @nomennescio !!

**Comment by nomennescio** [comment]
Hi @erg, didn't have time to check this one. Great job, but it seems the 'replace' object is still missing.

You need to fetch that manually from my repo, before I can proceed to #2197.

Run:
`git fetch <reference to my forked repo> refs/replace/*:refs/replace/*`

When then looking at all branches with git gui / gitk, the replace object should look like:

![CropperCapture 43](https://user-images.githubusercontent.com/24315005/79212673-3929b080-7e48-11ea-9b10-cd15480ccd2a.png)

Then the whole history is connected and diffs and merges between ALL points can be made.

**Comment by nomennescio** [comment]
Hi @erg. It also seems the 'release' branch is still missing:

```
$ git branch -r
  origin/HEAD -> origin/master
  origin/char-rename
  origin/clean-linux-x86-32
  origin/clean-linux-x86-64
  origin/clean-macosx-x86-32
  origin/clean-macosx-x86-64
  origin/clean-windows-x86-32
  origin/clean-windows-x86-64
  origin/cvs
  origin/darcs
  origin/db4
  origin/dragonfly
  origin/elevate-erg
  origin/factor-shell
  origin/fix-linux
  origin/freebsd-work
  origin/github/freebsd-work
  origin/handle-patch-and-put
  origin/html-help-styling
  origin/locals-and-roots
  origin/master
  origin/modern-harvey2
  origin/modern-harvey3
  origin/modern-harvey3-triple
  origin/modern-harvey4
  origin/paths
  origin/revert-2214-feature-commandline-documentation
  origin/travis-windows
  origin/unicode-12.1.0
  origin/vm-warnings
  origin/windows-drag
  origin/windows-high-dpi
```
Can you also fetch that branch into the repo?
Use

```
$ git fetch <my_forked_repo> release
$ git checkout -b release <my_forked_repo>/release
```

**Comment by mrjbq7** [comment]
I just pushed the release branch.

**Comment by nomennescio** [comment]
Thanks for pushing the release branch.

Could you also get the replace object as by the instructions above?

It will greatly help in rewriting history to fix the reported issues as in #2197 and #2278

**Comment by mrjbq7** [comment]
Doesn’t that replace object rewrite history and make existing git checkouts somehow incompatible? Isn’t that why we didn’t pull it before?

How do I look at what the replace object does?

**Comment by nomennescio** [comment]
> Doesn’t that replace object rewrite history and make existing git checkouts somehow incompatible? Isn’t that why we didn’t pull it before? How do I look at what the replace object does?

No, the replace object does not rewrite history. It's only single Git object that lives in `.git/refs/replace`
However, Git recognizes git replace objects and links to the parent using the info in such an object.

You can look at the git history without using such interpretation with
`git --no-replace-objects <command>`

If you don't like it, you can just throw the single object away from the directory.

Nothing else is changed.
