### ISSUE TITLE
autocomplete list shows used vocab as grey

### ISSUE THREAD

**Issue by erg** [factor/factor#2545]
I think it should show as not grey.

![Screenshot 2022-01-08 153222](https://user-images.githubusercontent.com/27430/148660693-6adc9672-980c-4cd6-be79-7a9dd2408e5b.png)

**Comment by mrjbq7** [comment]
Fixed by 5abf9c8604019c82b3d0bd6af8b592c64c86dacd.

**Comment by erg** [comment]
Some of the USE: lines show as black now, but try `USE: lint` and it still doesn't show ungreyed.

**Comment by erg** [comment]
The `manifest` is `f` or else we could just `using-vocab?` it.

**Comment by mrjbq7** [comment]
Right now black/red is for loaded vocabs, dark gray is unloaded vocabs.

has nothing to do with using

**Comment by mrjbq7** [comment]
I did USE: lint then USE: li<TAB> and its black just fine.

**Comment by mrjbq7** [comment]
It would be easy to change it to used vocabs using the manifest.  It's not stored in dynamic variable, it's a slot on ``interactor``.

**Comment by erg** [comment]
`all-disk-vocabs-recursive` was memoized and only reset on forgetting vocabs. changed it to reset after any vocab change. also fun fact, memoized survives through image reloads. ❗
